### ISSUE TITLE
Add SIGHUP handler to re-load configuration file

### ISSUE THREAD

**Issue by justintocci** [greyspots/envelope#4]
Opened from issue #2:

tylerknott wrote:
3) Why do you have an option to use hardcoded keys? 

Justin - Nunzio - Joseph:
This got us thinking. We should implement a SIGHUP that does not terminate the program but does reload the configuration file.

**Comment by josephtocci** [comment]
I have added the sighup handler, but the config file is not reread until the next time a connection comes in. I/O is not safe inside a handler, so I simply change a flag so we can reread when it is convenient.
